### ISSUE TITLE
Link to presentation in README does not work

### ISSUE THREAD

**Issue by astares** [badetitou/CORA#96]

**Comment by astares** [comment]
Link to https://badetitou.github.io/research/smalltalk/2017/08/21/SmartTest/

gives NOT FOUND

**Comment by badetitou** [comment]
Oops... you're right

Thanks!!

I update it, 
This is the good url

https://badetitou.github.io/projects/SmartTest/SmartTest/

**Comment by astares** [comment]
@badetitou 

Thanks - nice work! Adding a screenshot to the README would be cool too.
